services:
  litecoin-wallet-rpc:
    build: .
    ports:
      - "127.0.0.1:8101:8101" # bind to localhost, accessible outside docker network
    env_file:
      - .env
    environment:
      - ENV_FILE=/app/.env
    restart: unless-stopped
